### ISSUE TITLE
nil pointer dereference in test suite

### ISSUE THREAD

**Issue by nonce9** [nonce9/pwch#53]
Every now and then the test suite fails with a nil pointer dereference.

```
=== RUN   Test_SubmitEmailHandler
--- PASS: Test_SubmitEmailHandler (0.00s)
=== RUN   Test_EmailSendHandler
=== RUN   Test_EmailSendHandler/test_valid_email_address
--- FAIL: Test_EmailSendHandler (0.00s)
    --- FAIL: Test_EmailSendHandler/test_valid_email_address (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5c32d7]

goroutine 22 [running]:
testing.tRunner.func1.2({0x81e260, 0xb9ca50})
	/usr/lib/go-1.19/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	/usr/lib/go-1.19/src/testing/testing.go:1399 +0x39f
panic({0x81e260, 0xb9ca50})
	/usr/lib/go-1.19/src/runtime/panic.go:884 +0x212
database/sql.(*Stmt).Close(0x0)
	/usr/lib/go-1.19/src/database/sql/sql.go:2872 +0x37
panic({0x81e260, 0xb9ca50})
	/usr/lib/go-1.19/src/runtime/panic.go:884 +0x212
database/sql.(*Stmt).QueryContext(0x0, {0x939450, 0xc00019c000}, {0xc0001d5c20, 0x2, 0x2})
	/usr/lib/go-1.19/src/database/sql/sql.go:2767 +0x82
database/sql.(*Stmt).QueryRowContext(0x88954a?, {0x939450?, 0xc00019c000?}, {0xc0001d5c20?, 0x53?, 0xbaf9c0?})
	/usr/lib/go-1.19/src/database/sql/sql.go:2845 +0x2c
database/sql.(*Stmt).QueryRow(...)
	/usr/lib/go-1.19/src/database/sql/sql.go:2867
github.com/nonce9/pwch/internal/pwch.emailEnabled({0x889544?, 0xc0001c4cc0?})
	/pwch/internal/pwch/mail.go:150 +0x2f3
github.com/nonce9/pwch/internal/pwch.EmailSendHandler({0x938ee8, 0xc0001c4cc0}, 0xc000220100)
	/pwch/internal/pwch/handler.go:102 +0x166
github.com/nonce9/pwch/internal/pwch.Test_EmailSendHandler.func1({0x802700?, 0x0?}, {0x88fd14, 0x1b}, {0x87f68b, 0x4}, 0xc8, 0x1)
	/pwch/internal/pwch/handler_test.go:96 +0x21b
github.com/nonce9/pwch/internal/pwch.Test_EmailSendHandler.func2(0xc00018d860)
	/pwch/internal/pwch/handler_test.go:127 +0x128
testing.tRunner(0xc00018d860, 0xc000196348)
	/usr/lib/go-1.19/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/usr/lib/go-1.19/src/testing/testing.go:1493 +0x35f
```

It's probably tied to the deferred Close() of the prepared statement but I can't pinpoint it at the moment.

**Comment by nonce9** [comment]
Seems to be fixed by improved error handling.
